# Generated by Django 4.0.5 on 2022-06-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lluvia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_lluvia', models.DateField()),
                ('probabilidad_lluvia', models.FloatField()),
                ('precipitaciones', models.FloatField()),
                ('fecha_pronostico', models.DateField()),
            ],
        ),
    ]
